openapi: 3.0.0
info:
  version: ''
  title: Payment Processing
  contact: {}
  description: 'Process payments using payment instrument such as credit card. See [Payments Overview](https://developer.bigcommerce.com/api-docs/store-management/payment-processing) for more information.'
tags:
  - name: Accepted Methods
  - name: Access Tokens
  - name: Process Payment
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
servers:
  - url: 'https://api.bigcommerce.com/stores/{$$.env.store_hash}/v3'
    variables:
      $$.env.store_hash:
        default: store_hash
  - url: 'https://payments.bigcommerce.com/stores/{$$.env.store_hash}'
    variables:
      $$.env.store_hash:
        default: store_hash
security:
  - X-Auth-Client: []
  - X-Auth-Token: []
paths:
  /payments:
    post:
      summary: Process Payment
      tags:
        - Process Payment
      operationId: PaymentsPost
      description: 'Process payments for an order. See [Payment Processing](https://developer.bigcommerce.com/api-docs/store-management/payment-processing) for more information.'
      servers:
        - url: 'https://payments.bigcommerce.com/stores/{$$.env.store_hash}'
          variables:
            $$.env.store_hash:
              default: store_hash
      parameters:
        - name: Authorization
          in: header
          required: true
          description: 'Authorization header with a valid payment access token is required to access this endpoint e.g. Authorization: PAT a-valid-payment-access-token'
          schema:
            type: string
            example: 'PAT {PAT} '
        - name: Accept
          in: header
          schema:
            type: string
            enum:
              - application/vnd.bc.v1+json
            default: application/vnd.bc.v1+json
        - name: Content-Type
          in: header
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              title: Payment Request
              type: object
              properties:
                payment:
                  title: Payment
                  type: object
                  required:
                    - instrument
                    - payment_method_id
                  properties:
                    instrument:
                      oneOf:
                        - $ref: '#/components/schemas/Card'
                        - $ref: '#/components/schemas/StoredCard'
                        - $ref: '#/components/schemas/StoredPaypalAccount'
                    payment_method_id:
                      description: Identifier for payment method that will be used for this payment and `id` from the Get Accepted Payment Methods API
                      type: string
                      minLength: 1
              required:
                - payment
            examples:
              Card:
                value:
                  payment:
                    instrument:
                      type: card
                      cardholder_name: string
                      number: string
                      expiry_month: 1
                      expiry_year: 0
                      verification_value: stri
                      issue_month: 1
                      issue_year: 0
                      issue_number: 0
                    payment_method_id: string
              Stored Card:
                value:
                  payment:
                    instrument:
                      type: stored_card
                      token: 8cdf7b6ea1b27119463bf9e5106639618cc77a9adc49f0069ca8b756cc15caee
                      verification_value: '1142'
                    payment_method_id: adyenv2.scheme
        required: true
        x-examples:
          application/json:
            payment:
              instrument: {}
              payment_method_id: Lorem in
              amount: 81505146
              currency_code: NYE
          Payment Access Token: |-
            curl -X POST \
              https://payments.bigcommerce.com/stores/{$$.env.store_hash}/payments \
              -H 'Accept: application/vnd.bc.v1+json' \
              -H 'Authorization: PAT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NsdfasftIsIm5iZiI6MTU1MTM5MDU0MiwiaXNzIjoicGF5bWVudHMuYmlnY29tbWVyY2UuY29tIiwic3ViIjoianJhaDZnbW4iLCJqdGkiOiI3Nzg3ZmU1Zi01OWJmLTQ3ZWMtYTFmZC00ZDQ3ZTkwNjFlNWMiLCJpYXQiOjE1NTEzOTA1NDIsImRhdGEiOnsic3RvcmVfaWQiOjEwMjU2NDYsIm9yZGVyX2lkIjoyMTUsImFtb3VudCI6OTgwMCwiY3VycmVuY3kiOiJVU0QifX0.WbR90d8m4gn8wK7kPMDEoVq8B0hHC5Ul5H4Hpqq6Yvo' \
              -H 'Content-Type: application/json' \
          Vaulted Card:
            payment:
              instrument:
                type: stored_card
                token: vaulted instrument token
                verification_value: '123'
              payment_method_id: stripe.card
              save_instrument: true
          Credit Card: |-
            {
              "payment": {
                "instrument": {
                  "type": "card",
                  "number": "4111111111111111",
                  "cardholder_name": "BP",
                  "expiry_month": 12,
                  "expiry_year": 2020,
                  "verification_value": "411"
                },
                "payment_method_id": "authorizenet.card",
                 "save_instrument": true
              }
            }
        description: ''
      responses:
        '202':
          description: Payment has been successfully processed
          content:
            application/json:
              schema:
                title: Success Payment Response
                type: object
                properties:
                  id:
                    description: Identifier for this transaction
                    type: string
                  transaction_type:
                    title: Transaction Type
                    description: Transaction type for this payment
                    example: authorization
                    type: string
                    enum:
                      - authorization
                      - purchase
                  status:
                    type: string
                    title: Status
                    description: Status to indicate a success response
                    enum:
                      - success
                      - pending
              examples:
                response:
                  value:
                    id: 227d9e1e-94f8-408c-95a5-f97b30592eb7
                    transaction_type: authorization
                    status: pending
        '400':
          description: Payment request has been rejected due to malformed request
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: 'Payment request has been rejected due to missing, invalid data or declined by payment provider'
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
  /payments/access_tokens:
    post:
      description: |-
        This endpoint provides the capability to create a payment access token. The payment access token is required when making request to Payment API for submitting payment for an order.

        After the token is created then use the token to [Process Payments](/api-reference/payments/payments-process-payments/payment/paymentspost).

        **Required Fields**
        * order_id
      summary: Create Payment Access Token
      tags:
        - Access Tokens
      operationId: PaymentsAccessTokensPost
      servers:
        - url: 'https://api.bigcommerce.com/stores/{$$.env.store_hash}/v3'
          variables:
            $$.env.store_hash:
              default: store_hash
      deprecated: false
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
        - in: header
          name: Content-Type
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              title: Payment Access Token Request
              type: object
              properties:
                order:
                  $ref: '#/components/schemas/Order'
              required:
                - order
            examples:
              example-1:
                value:
                  order:
                    id: 1
                    is_recurring: false
        required: true
        x-examples:
          application/json:
            order:
              id: 44796008
              is_recurring: true
          Example:
            order:
              id: 182
      responses:
        '201':
          description: Payment access token has been successfully created
          headers: {}
          content:
            application/json:
              schema:
                title: Payments Access Tokens Response
                type: object
                properties:
                  data:
                    title: Payment Access Token
                    type: object
                    properties:
                      id:
                        description: Payment access token. This token is required in subsequent payment request to Payment API endpoint.
                        type: string
                        minLength: 1
                    required:
                      - id
              examples:
                example-1:
                  value:
                    data:
                      id: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTUyNTA3NTksIm5iZiI6MTYxNTI0Nz E1OSwiaXNzIjoicGF5bWVudHMuYmlnY29tbWVyY2UuY29tIiwic3ViIjoieHNsM3 JoZGYzNiIsImp0aSI6IjNhOGE3NTJjLTBmNWQtNDNmNS05MzdjLTRhMTYzODBlMW YwZCIsImlhdCI6MTYxNTI0NzE1OSwiZGF0YSI6eyJzdG9yZV9pZCI6IjEwMDEzMz YzMjQiLCJvcmRlcl9pZCI6IjE2NiIsImFtb3VudCI6NDU3OTAsImN1cnJlbmN5Ij oiVVNEIn19.dpCDgOfbNrz095VARY20yYBRTOuq-W1F0ETTgf1Zhbs
                    meta: {}
        '400':
          description: Request has been rejected
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '404':
          description: Request has been rejected due to resource not being found
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '409':
          description: Request has been rejected due to conflict with the current state of the target resource
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: Request has been rejected due to missing or invalid data
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
  /payments/methods:
    get:
      description: |-
        Returns a list of accepted payment methods based on the `order_id`.

        **Required Fields**
        * order_id
      summary: Get Accepted Payment Methods
      tags:
        - Accepted Methods
      operationId: PaymentsMethodsGet
      servers:
        - url: 'https://api.bigcommerce.com/stores/{$$.env.store_hash}/v3'
          variables:
            $$.env.store_hash:
              default: store_hash
      deprecated: false
      parameters:
        - name: order_id
          in: query
          required: false
          description: Identifier for the order
          schema:
            type: integer
            format: int32
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
        - in: header
          name: Content-Type
          schema:
            type: string
            default: application/json
      responses:
        '200':
          $ref: '#/components/responses/paymentsMethods_Resp'
        '400':
          description: Request has been rejected
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '404':
          description: Request has been rejected due to resource not being found
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: Request has been rejected due to missing or invalid data
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
            examples:
              example-1:
                value:
                  order_id: 0
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
components:
  parameters:
    Accept:
      name: Accept
      in: header
      schema:
        type: string
        enum:
          - application/vnd.bc.v1+json
        default: application/vnd.bc.v1+json
    Content-Type:
      name: Content-Type
      in: header
      schema:
        type: string
        default: application/json
  responses:
    paymentsMethods_Resp:
      description: ''
      content:
        application/json:
          schema:
            title: Payments Methods Response
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/paymentMethod_Full'
          examples:
            response:
              value:
                data:
                  - id: stripe.card
                    name: Stripe
                    test_mode: true
                    type: card
                    supported_instruments:
                      - instrument_type: VISA
                        verification_value_required: true
                      - instrument_type: MASTERCARD
                        verification_value_required: true
                      - instrument_type: AMEX
                        verification_value_required: true
                      - instrument_type: DISCOVER
                        verification_value_required: true
                      - instrument_type: JCB
                        verification_value_required: true
                      - instrument_type: DINERS_CLUB
                        verification_value_required: true
                      - instrument_type: STORED_CARD
                        verification_value_required: true
                    stored_instruments:
                      - type: stored_card
                        brand: VISA
                        expiry_month: 9
                        expiry_year: 2020
                        issuer_identification_number: '424242'
                        last_4: '4242'
                        token: 050a1e5c982e5905288ec5ec33f292772762033a0704f46fccb16bf1940b51ef
                        is_default: true
                meta: {}
    paymentAccessToken_Resp:
      description: ''
      content:
        application/json:
          schema:
            title: Payments Access Tokens Response
            type: object
            properties:
              data:
                $ref: '#/components/schemas/PaymentAccessToken'
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |-
        ### OAuth Scopes
        |  **UI Name** | **Permission** | **Parameter** |
        | --- | --- | --- |
        |  Create Payments | create | `store_payments_access_token_create` |
        |  Get Payment Methods | read-only | `store_payments_methods_read` |

        ### Headers

        |Header|Parameter|Description|
        |-|-|-|
        |`X-Auth-Token`|`ACCESS_TOKEN`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|
        |`Authorization`|`{PAYMENT_ACCESS_TOKEN}`|Obtained using Create Access Token endpoint.|

        ### Example

        ```http
        POST /stores/{$$.env.store_hash}/v3/payments/access_tokens
        host: api.bigcommerce.com
        Content-Type: application/json
        X-Auth-Token: {ACCESS_TOKEN}
        ```

        ```http
        POST /payments
        host: payments.bigcommerce.com
        Content-Type: application/json
        Authorization: {PAYMENT_ACCESS_TOKEN}
        ```

        * For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).
  schemas:
    PaymentRequest:
      title: Payment Request
      type: object
      properties:
        payment:
          title: Payment
          type: object
          required:
            - instrument
            - payment_method_id
          properties:
            amount:
              description: Amount in smallest currency unit
              type: integer
              format: int32
            currency_code:
              description: Currency code
              type: string
              pattern: '^[A-Z]{3}$'
            instrument:
              description: ''
              type: object
            payment_method_id:
              description: Identifier for payment method that will be used for this payment
              type: string
              minLength: 1
      required:
        - payment
    Payment:
      title: Payment
      type: object
      properties:
        amount:
          description: Amount in smallest currency unit
          type: integer
          format: int32
        currency_code:
          description: Currency code
          type: string
          pattern: '^[A-Z]{3}$'
        instrument:
          description: ''
          type: object
        payment_method_id:
          description: Identifier for payment method that will be used for this payment
          type: string
          minLength: 1
      required:
        - instrument
        - payment_method_id
    SuccessPaymentResponse:
      title: Success Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
        status:
          type: string
          title: Status
          description: Status to indicate a success response
          enum:
            - success
            - pending
    TransactionType:
      title: Transaction Type
      description: Transaction type for this payment
      example: authorization
      type: string
      enum:
        - authorization
        - purchase
    Status:
      type: string
      title: Status
      description: Status to indicate a success response
      enum:
        - success
        - pending
    ErrorPaymentResponse:
      title: Error Payment Response
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
        errors:
          description: ''
          type: object
          additionalProperties:
            type: string
      required:
        - status
        - title
        - type
    Card:
      title: Card
      type: object
      properties:
        type:
          description: Type to classify this payment instrument
          example: card
          type: string
          default: card
        cardholder_name:
          description: Cardholder's full name
          type: string
          minLength: 1
        number:
          description: Credit card number
          type: string
          minLength: 1
        expiry_month:
          description: Expiry month of this card
          type: integer
          minimum: 1
          maximum: 12
          format: int32
        expiry_year:
          description: Expiry year of this card
          type: integer
          format: int32
        verification_value:
          description: Verification value of this card
          type: string
          minLength: 3
          maxLength: 4
        issue_month:
          description: Issue month of this card
          type: integer
          minimum: 1
          maximum: 12
          format: int32
        issue_year:
          description: Issue year of this card
          type: integer
          format: int32
        issue_number:
          description: Issue number of this card
          type: integer
          format: int32
      required:
        - type
        - cardholder_name
        - number
        - expiry_month
        - expiry_year
      x-examples:
        example-1:
          type: card
          cardholder_name: string
          number: string
          expiry_month: 1
          expiry_year: 0
          verification_value: stri
          issue_month: 1
          issue_year: 0
          issue_number: 0
    StoredCard:
      title: Stored Card
      type: object
      properties:
        type:
          description: Type to classify this payment instrument
          example: stored_card
          type: string
          default: stored_card
        token:
          description: Identifier representing this stored card
          type: string
          minLength: 64
          maxLength: 64
      required:
        - type
        - token
    BasePaymentResponse:
      title: Base Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
    PendingPaymentResponse:
      title: Pending Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
        status:
          type: string
          title: Status
          description: Status to indicate a success response
          enum:
            - success
            - pending
    StoredPaypalAccount:
      title: StoredPaypalAccount
      type: object
      properties:
        type:
          type: string
          description: Type to classify this payment instrument
          enum:
            - stored_paypal_account
        token:
          description: Identifier representing this stored paypal account
          type: string
          minLength: 64
          maxLength: 64
      required:
        - type
        - token
    Order:
      title: Order
      type: object
      properties:
        id:
          description: Identifier for the order
          type: integer
          minimum: 1
          format: int32
        is_recurring:
          description: Whether this is a recurring order. If the order is recurring this field should be set to true in order to let the payment gateway know.
          example: false
          type: boolean
          default: false
      required:
        - id
      x-examples:
        example-1:
          id: 1
          is_recurring: false
    PaymentAccessTokenRequest:
      title: Payment Access Token Request
      type: object
      properties:
        order:
          title: Order
          type: object
          required:
            - id
          properties:
            id:
              description: Identifier for the order
              type: integer
              minimum: 1
              format: int32
            is_recurring:
              description: Whether this is a recurring order. If the order is recurring this field should be set to true in order to let the payment gateway know.
              example: false
              type: boolean
              default: false
      required:
        - order
    PaymentAccessToken:
      title: Payment Access Token
      type: object
      properties:
        id:
          description: Payment access token. This token is required in subsequent payment request to Payment API endpoint.
          type: string
          minLength: 1
      required:
        - id
    paymentMethodStoredInstrument:
      title: paymentMethodStoredInstrument
      type: object
      properties:
        brand:
          description: Brand of this card such as VISA or Mastercard
          type: string
          minLength: 1
        expiry_month:
          description: Expiry month of this card
          type: integer
          minimum: 1
          maximum: 12
          format: int32
        expiry_year:
          description: Expiry year of this card
          type: integer
          format: int32
        issuer_identification_number:
          description: Issuer identification number of this card. This is extracted from the card when the order is payed for.
          type: string
          minLength: 6
          maxLength: 6
        last_4:
          description: Last four numbers of this card
          type: string
          minLength: 4
          maxLength: 4
        token:
          description: 'Identifier representing this stored card. This is used to identify cards within BigCommerce. It is the same as the `payment_access_token` that returns via the [Get Transactions endpoint](https://developer.bigcommerce.com/api-reference/orders/orders-transactions-api/orders/gettransactions).'
          type: string
          minLength: 64
          maxLength: 64
        is_default:
          description: Whether this instrument is a default instrument
          example: false
          type: boolean
          default: false
        type:
          description: Type to classify this stored card
          example: stored_card
          type: string
          default: stored_card
      required:
        - brand
        - expiry_month
        - expiry_year
        - issuer_identification_number
        - last_4
        - token
        - is_default
        - type
      x-examples:
        example-1:
          brand: string
          expiry_month: 1
          expiry_year: 0
          issuer_identification_number: string
          last_4: stri
          token: stringstringstringstringstringstringstringstringstringstringstri
          is_default: false
          type: stored_card
    paymentMethod_Full:
      title: paymentMethod_Full
      type: object
      properties:
        id:
          description: Identifier for this payment method
          type: string
          minLength: 1
        name:
          description: Name of this payment method
          type: string
          minLength: 1
        stored_instruments:
          type: array
          items:
            $ref: '#/components/schemas/paymentMethodStoredInstrument'
        supported_instruments:
          type: array
          items:
            title: Supported Card Instrument
            type: object
            properties:
              instrument_type:
                title: InstrumentType
                description: Type of this instrument
                example: VISA
                type: string
                enum:
                  - VISA
                  - MASTERCARD
                  - DISCOVER
                  - AMEX
                  - DINERS_CLUB
                  - JCB
                  - DANKORT
                  - MAESTRO
                  - STORED_CARD
              verification_value_required:
                description: Whether verification value is required for payment
                type: boolean
            required:
              - instrument_type
        test_mode:
          description: Whether this payment method is on test mode
          example: false
          type: boolean
          default: false
        type:
          description: Type to classify this payment method
          example: card
          type: string
          default: card
      required:
        - id
        - name
        - supported_instruments
        - test_mode
        - type
      x-examples:
        example-1:
          id: string
          name: string
          stored_instruments:
            - brand: string
              expiry_month: 1
              expiry_year: 0
              issuer_identification_number: string
              last_4: stri
              token: stringstringstringstringstringstringstringstringstringstringstri
              is_default: false
              type: stored_card
          supported_instruments:
            - instrument_type: VISA
              verification_value_required: true
          test_mode: false
          type: card
    SupportedCardInstrument:
      title: Supported Card Instrument
      type: object
      properties:
        instrument_type:
          title: InstrumentType
          description: Type of this instrument
          example: VISA
          type: string
          enum:
            - VISA
            - MASTERCARD
            - DISCOVER
            - AMEX
            - DINERS_CLUB
            - JCB
            - DANKORT
            - MAESTRO
            - STORED_CARD
        verification_value_required:
          description: Whether verification value is required for payment
          type: boolean
      required:
        - instrument_type
    Error:
      title: Error
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
      required:
        - status
        - title
        - type
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
        errors:
          type: object
          additionalProperties:
            type: string
      required:
        - status
        - title
        - type
    InstrumentType:
      title: InstrumentType
      description: Type of this instrument
      example: VISA
      type: string
      enum:
        - VISA
        - MASTERCARD
        - DISCOVER
        - AMEX
        - DINERS_CLUB
        - JCB
        - DANKORT
        - MAESTRO
        - STORED_CARD
    StoredPaypalAccountInstrument:
      title: StoredPaypalAccountInstrument
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email address of this stored account
        token:
          type: string
          description: Identifier representing this stored account
          minLength: 64
          maxLength: 64
        is_default:
          type: boolean
          description: Whether this instrument is a default instrument
          default: false
        type:
          type: string
          description: Type to classify this stored account
          enum:
            - stored_paypal_account
      required:
        - email
        - token
        - is_default
        - type
    SupportedPaypalAccountInstrument:
      title: SupportedPaypalAccountInstrument
      type: object
      properties:
        instrument_type:
          type: string
          description: Type of this instrument
          enum:
            - STORED_PAYPAL_ACCOUNT
      required:
        - instrument_type
